# Generated by Django 5.0.6 on 2024-05-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=11, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('davomiyligi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=50)),
                ('tajriba', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=33, unique=True)),
                ('phone_num', models.DecimalField(decimal_places=0, max_digits=13, unique=True)),
                ('parents_phone_num', models.DecimalField(decimal_places=0, max_digits=13, unique=True)),
                ('telegram_link', models.CharField(max_length=41, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.courses')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.teachers')),
            ],
        ),
    ]
